name: onebody
homepage: https://church.io/onebody
description:  private member portal for churches, built with Ruby on Rails
changelog: RELEASES.md
license: AGPL
dependencies:
  - mysql-server
  - libxml2
  - imagemagick
compile_cache_dir: /tmp/pkgr-cache
after_install: build/deb/script/post-install
store_cache: true
