# this config file is for installer.71m.us

name: OneBody
image: ubuntu-14-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: onebody
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - wget
  runcmd:
    - su -l onebody -c "cd /tmp && wget https://raw.githubusercontent.com/seven1m/onebody/master/build/ubuntu/14.04/provision.sh && bash provision.sh"
