# this config file is for installer.71m.us

name: OneBody
image: ubuntu-16-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: onebody
      groups: sudo
      shell: /bin/bash
  packages:
    - wget
  runcmd:
    - "cd /tmp && wget https://raw.githubusercontent.com/seven1m/onebody/master/build/ubuntu/16.04/provision.sh && bash provision.sh"
