production:
  adapter: sqlite3 
  database: db/production.db 
  # or... 
  # adapter: mysql 
  # database: onebody 
  # username: root 
  # password:

development:
  adapter: sqlite3 
  database: db/dev.db 
  # or... 
  # adapter: mysql 
  # database: onebody_dev
  # username: root 
  # password:

test:
  adapter: sqlite3
  database: db/test.db
  # or...
  # adapter: mysql
  # database: onebody_test
  # username: root
  # password: