development:
  adapter: mysql
  database: crccweb
  username: root
  password: 

test:
  adapter: sqlite3
  database: db/test.db

production:
  adapter: mysql
  database: crccweb
  username: root
  password: 
  host: localhost
