development:
  adapter: mysql
  database: onebody_dev
  username: root
  password: 

test:
  adapter: mysql
  database: onebody_test
  username: root
  password: 

production:
  adapter: mysql
  database: onebody
  username: root
  password: 
