production:
  adapter: mysql
  database: onebody_new
  username: onebody
  password: onebody

development:
  production

test:
  adapter: sqlite3
  database: db/test.db
  # or...
  # adapter: mysql
  # database: onebody_test
  # username: root
  # password:
