development:
  adapter: mysql
  database: beonebody_dev
  username: root
  password: 

test:
  adapter: mysql
  database: beonebody_test
  username: root
  password: 

production:
  adapter: mysql
  database: beonebody
  username: root
  password: 
