--- 
Contact: 
  Tech Support Email:
    format: string
    value: admin@example.com
    global: true
  Community Email:
    format: string
    value: info@beonebody.com
  Community Office Phone:
    format: string
    value: (123) 456-7890
  Bug Notification Email: 
    format: string
    value: 
    global: true
  Birthday Verification Email: 
    format: string
    value: admin@beonebody.com
  Send Email Changes To: 
    format: string
    value: admin@beonebody.com
  Community Address: 
    format: string
    value: 123 West Imaginary Street, Broken Arrow, OK 12345-6789
  Send Updates To:
    format: string
    value: admin@beonebody.com
Name: 
  Community: 
    format: string
    value: One Church
  Site: 
    format: string
    value: One Church
  Slogan: 
    format: string
    value: Welcome home.
Features: 
  Multisite: 
    format: boolean
    value: false
    global: true
  SSL: 
    format: boolean
    value: false
    global: true
  Sign Up: 
    format: boolean
    value: false
  Groups: 
    format: boolean
    value: true
  Pictures: 
    format: boolean
    value: true
  Notes:
    format: boolean
    value: true
  Friends: 
    format: boolean
    value: true
  Sign Up Approval Email: 
    format: string
    value: 
  Verses: 
    format: boolean
    value: true
  Recipes: 
    format: boolean
    value: false
  Updates Must Be Approved:
    format: boolean
    value: true
  Edit Legacy Ids:
    format: boolean
    value: false
    global: true
  Custom Person Type:
    format: boolean
    value: false
  Custom Person Fields:
    format: list
    value:
  Community Google Calendar: 
    format: string
    value:
  News Page:
    format: boolean
    value: true
  News by Users:
    format: boolean
    value: true
Services: 
  Yahoo: 
    format: string
    value: 
    global: true
  Analytics: 
    format: string
    value: 
URL: 
  Visitor: 
    format: string
    value: http://beonebody.com
  Site: 
    format: string
    value: http://beonebody.com/
    hidden: true
  News Feed: 
    format: string
    value: 
System:
  Language:
    format: string
    value: en
  Suffixes: 
    format: list
    value: |
      --- 
      - Jr.
      - Sr.
      - II
      - III

  Time Zone: 
    format: string
    value: Central Time (US & Canada)
  Online Only Relationships:
    format: list
    hidden: true
    value:
  Adult Age:
    format: string
    value: 18
Formats: 
  Full Date and Time: 
    format: string
    value: "%m/%d/%Y %I:%M %p"
  Time: 
    format: string
    value: "%I:%M %p"
  Phone: 
    format: string
    value: (ddd) ddd-dddd
  Mobile Phone: 
    format: string
    value: (ddd) ddd-dddd
  Date: 
    format: string
    value: "%m/%d/%Y"
  Date Without Year: 
    format: string
    value: "%m/%d"
Appearance: 
  Theme Primary Color:
    format: string
    value: 5F9128
  Theme Secondary Color:
    format: string
    value: 3286B5
  Theme Top Color:
    format: string
    value: 333333
  Theme Nav Color:
    format: string
    value: E4E4E4
Privacy: 
  Allow Unencrypted Logins: 
    format: boolean
    value: false
  Relay All Email: 
    format: boolean
    value: true
  Max Sign in Attempts: 
    format: string
    value: 10
  Share Address by Default:
    format: boolean
    value: true
  Share Home Phone by Default:
    format: boolean
    value: true
  Share Mobile Phone by Default:
    format: boolean
    value: false
  Share Work Phone by Default:
    format: boolean
    value: false
  Share Fax by Default:
    format: boolean
    value: false
  Share Email by Default:
    format: boolean
    value: false
  Share Birthday by Default:
    format: boolean
    value: true
  Share Anniversary by Default:
    format: boolean
    value: true
  Allow Picture Comments:
    format: boolean
    value: true
  Hide Contact Details in Messages:
    format: boolean
    value: true
